config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'affirmations#landing'
  resources :affirmations, only: %i[new create]
  patch 'developers/:developer_uuid/confirm', to: 'developers#confirm', defaults: {format: "xml"}
  get 'developers/:developer_uuid/confirm', to: 'developers#preconfirm', as: 'preconfirm', defaults: {format: "xml"}
  post '/twilio/receive', to: 'developers#receive'
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
  has_many :developers
  has_many :developers, through: :sent_affirmation
  validates_presence_of :affirmation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/routeable.rb
# frozen_string_literal: true
module Routeable
  extend ActiveSupport::Concern

  included do
    include Rails.application.routes.url_helpers
  end

  def default_url_options
    Rails.application.config.action_mailer.default_url_options
  end
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :affirmations
  has_many :affirmations, through: :sent_affirmations
  validates_presence_of :phone_number
  before_create :generate_uuid
  scope :confirmed, -> { where(confirmed: true) }
  scope :to_be_deleted, -> { where(confirmed: false).where("created_at >": (Date.today - 2.days)) }

  private
  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/models/sent_affirmation.rb
class SentAffirmation < ApplicationRecord
  belongs_to :developer
  belongs_to :affirmation
end

app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController

  def landing
    render 'landing'
  end
  
  def new
    @affirmation = Affirmation.new
  end

  def create
    @affirmation = Affirmation.create(affirmation_params)
    redirect_to root_path, notice: 'Your affirmation has been created! How about another one?'
  end

  private
  def affirmation_params
    params.require(:affirmation).permit(:affirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def receive
    req_body = params['Body'].downcase
    if (req_body == 'affirm') || (req_body == 'start')
      create
    elsif req_body == 'stop'
      delete
    end
  end

  def create
    @dev = Developer.create!(phone_number: params[:From])
    uuid = @dev.uuid
    twiml = Twilio::TwiML::MessagingResponse.new do |r|
      r.message body: "Hi! You registered to receive developer affirmations. Confirm your registration here: #{preconfirm_url(uuid)} . If you don't confirm, your number will be deleted from the database in 2 days."
    end

    render xml: twiml.to_xml
  end

  def delete
    @dev = Developer.find_by_phone_number(params[:From])
    @dev.delete
  end

  def preconfirm
    confirm
  end

  private
  def confirm
    @dev = Developer.find_by_uuid(params[:developer_uuid])
    @dev.update!(confirmed: true)
    render plain: 'Your number has been confirmed!'
  end
end

app/helpers/affirmation_helper.rb
module AffirmationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/affirmations/landing.html.erb
<div class="col-md-10  mt-5">
  <h1>Affirmations for developers</h1>

  <p>Does your failing test suite get you down? Do you spend late nights bug hunting
    only to discover the culprit was a semi-colon?</p>
  <p>Sign up for weekly affirmations just for you! Text "AFFIRM" to <%= ENV['TWILIO_NUMBER']%> now!</p>
  <p>Or, if you have wisdom to share, why not <%= link_to "submit an affirmation", new_affirmation_path %>.</p>

</div>

<!--offset-md-3-->

app/views/affirmations/new.html.erb
<div class="col-md-6 offset-md-3 mt-5">
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <h1>Submit an Affirmation</h1>

    <%= form_for @affirmation  do |f| %>

        <div class="form-group">
            <%#= f.label :affirmation%><br />
            <%= f.text_area :affirmation, placeholder: "Submit your affirmation", id: "affirmation", class: "form-control", for: "affirmation" %>
        </div>
        <%= f.submit "Create", class: "btn cta"%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevAffirmations</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>